name: testexo2
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      -uses: actions/setup-python@v3
      -name: Test
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat requirements.txt
